services:
  aiops-nexus:
    image: webtechnelson/aiops-nexus:latest
    ports:
      - "8000:5000"
  open-webui:
    container_name: open-webui
    image: "ghcr.io/open-webui/open-webui:main"
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
      - "11434:11434"