Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant"

    # VM - Microk8s
    config.vm.define "microk8s" do |microk8s|
        # Ubuntu 22.04 lts
        microk8s.vm.box = "bento/ubuntu-22.04"
        microk8s.vm.hostname = "microk8s-server"
        microk8s.vm.network "private_network", ip: "192.168.70.10"

        microk8s.vm.network "forwarded_port", guest: 80, host: 8080

        microk8s.vm.provider "virtualbox" do |vb|
            vb.memory = 6144
            vb.cpus = 2
            vb.name = "ubuntu-vagrant-mikro8s"
        end

        # Initial VM bootstrap script
        microk8s.vm.provision "Provision vm shell script", type: "shell", path: "scripts/provision-microk8s.sh"
    end

end
