---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-nexus
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-nexus
  template:
    metadata:
      labels:
        app: aiops-nexus
    spec:
      containers:
      - name: aiops-nexus
        image: webtechnelson/aiops-nexus:1.1.0
        env:
        - name: WEBHOOK_URL
          value: https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # slack and discord are compatible at this moment
        - name: LLM
          value: llama3.2 # if LLM is left blank, pre-installed llama3.2 will be loaded
        imagePullPolicy: Always
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: aiops-nexus
  namespace: app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: aiops-nexus